// Generated by analysis/door-coverage/experiment.py --write.
export const doorCoverageData = {
  "window": 5000,
  "searchLimit": 1000000,
  "totalSmall": 667,
  "totalLarge": 78496,
  "coverage": [
    {
      "q": 5,
      "exponent": 1,
      "power": 5,
      "first": 11,
      "count": 162
    },
    {
      "q": 5,
      "exponent": 2,
      "power": 25,
      "first": 101,
      "count": 31
    },
    {
      "q": 5,
      "exponent": 3,
      "power": 125,
      "first": 251,
      "count": 10
    },
    {
      "q": 7,
      "exponent": 1,
      "power": 7,
      "first": 13,
      "count": 115
    },
    {
      "q": 7,
      "exponent": 2,
      "power": 49,
      "first": 97,
      "count": 16
    },
    {
      "q": 7,
      "exponent": 3,
      "power": 343,
      "first": 1373,
      "count": 2
    },
    {
      "q": 11,
      "exponent": 1,
      "power": 11,
      "first": 23,
      "count": 69
    },
    {
      "q": 11,
      "exponent": 2,
      "power": 121,
      "first": 241,
      "count": 6
    },
    {
      "q": 11,
      "exponent": 3,
      "power": 1331,
      "first": 2663,
      "count": 1
    },
    {
      "q": 13,
      "exponent": 1,
      "power": 13,
      "first": 53,
      "count": 56
    },
    {
      "q": 13,
      "exponent": 2,
      "power": 169,
      "first": 337,
      "count": 4
    },
    {
      "q": 13,
      "exponent": 3,
      "power": 2197,
      "first": 30757,
      "count": 0
    },
    {
      "q": 17,
      "exponent": 1,
      "power": 17,
      "first": 67,
      "count": 42
    },
    {
      "q": 17,
      "exponent": 2,
      "power": 289,
      "first": 577,
      "count": 2
    },
    {
      "q": 17,
      "exponent": 3,
      "power": 4913,
      "first": 78607,
      "count": 0
    },
    {
      "q": 19,
      "exponent": 1,
      "power": 19,
      "first": 37,
      "count": 39
    },
    {
      "q": 19,
      "exponent": 2,
      "power": 361,
      "first": 2887,
      "count": 1
    },
    {
      "q": 19,
      "exponent": 3,
      "power": 6859,
      "first": 27437,
      "count": 0
    },
    {
      "q": 23,
      "exponent": 1,
      "power": 23,
      "first": 47,
      "count": 33
    },
    {
      "q": 23,
      "exponent": 2,
      "power": 529,
      "first": 4231,
      "count": 1
    },
    {
      "q": 23,
      "exponent": 3,
      "power": 12167,
      "first": 194671,
      "count": 0
    },
    {
      "q": 29,
      "exponent": 1,
      "power": 29,
      "first": 59,
      "count": 24
    },
    {
      "q": 29,
      "exponent": 2,
      "power": 841,
      "first": 13457,
      "count": 0
    },
    {
      "q": 29,
      "exponent": 3,
      "power": 24389,
      "first": 48779,
      "count": 0
    },
    {
      "q": 31,
      "exponent": 1,
      "power": 31,
      "first": 61,
      "count": 20
    },
    {
      "q": 31,
      "exponent": 2,
      "power": 961,
      "first": 7687,
      "count": 0
    },
    {
      "q": 31,
      "exponent": 3,
      "power": 29791,
      "first": 59581,
      "count": 0
    },
    {
      "q": 37,
      "exponent": 1,
      "power": 37,
      "first": 73,
      "count": 16
    },
    {
      "q": 37,
      "exponent": 2,
      "power": 1369,
      "first": 5477,
      "count": 0
    },
    {
      "q": 37,
      "exponent": 3,
      "power": 50653,
      "first": 202613,
      "count": 0
    },
    {
      "q": 41,
      "exponent": 1,
      "power": 41,
      "first": 83,
      "count": 17
    },
    {
      "q": 41,
      "exponent": 2,
      "power": 1681,
      "first": 3361,
      "count": 1
    },
    {
      "q": 41,
      "exponent": 3,
      "power": 68921,
      "first": null,
      "count": 0
    },
    {
      "q": 43,
      "exponent": 1,
      "power": 43,
      "first": 173,
      "count": 17
    },
    {
      "q": 43,
      "exponent": 2,
      "power": 1849,
      "first": 3697,
      "count": 1
    },
    {
      "q": 43,
      "exponent": 3,
      "power": 79507,
      "first": 159013,
      "count": 0
    }
  ],
  "thresholds": [
    {
      "ingredients": 1,
      "prime": 5,
      "door": 4,
      "factors": [
        [
          2,
          2
        ]
      ]
    },
    {
      "ingredients": 2,
      "prime": 11,
      "door": 10,
      "factors": [
        [
          2,
          1
        ],
        [
          5,
          1
        ]
      ]
    },
    {
      "ingredients": 3,
      "prime": 71,
      "door": 70,
      "factors": [
        [
          2,
          1
        ],
        [
          5,
          1
        ],
        [
          7,
          1
        ]
      ]
    },
    {
      "ingredients": 4,
      "prime": 769,
      "door": 770,
      "factors": [
        [
          2,
          1
        ],
        [
          5,
          1
        ],
        [
          7,
          1
        ],
        [
          11,
          1
        ]
      ]
    },
    {
      "ingredients": 5,
      "prime": 10009,
      "door": 10010,
      "factors": [
        [
          2,
          1
        ],
        [
          5,
          1
        ],
        [
          7,
          1
        ],
        [
          11,
          1
        ],
        [
          13,
          1
        ]
      ]
    },
    {
      "ingredients": 6,
      "prime": 336491,
      "door": 336490,
      "factors": [
        [
          2,
          1
        ],
        [
          5,
          1
        ],
        [
          7,
          1
        ],
        [
          11,
          1
        ],
        [
          19,
          1
        ],
        [
          23,
          1
        ]
      ]
    }
  ],
  "ingredientCensus": [
    {
      "limit": 100,
      "total": 23,
      "count": 1
    },
    {
      "limit": 1000,
      "total": 166,
      "count": 54
    },
    {
      "limit": 10000,
      "total": 1227,
      "count": 693
    },
    {
      "limit": 100000,
      "total": 9590,
      "count": 6578
    },
    {
      "limit": 1000000,
      "total": 78496,
      "count": 59795
    }
  ],
  "overlaps": [
    {
      "a": 5,
      "b": 7,
      "countSmall": 31,
      "countLarge": 3259,
      "limitingDenominator": 24
    },
    {
      "a": 5,
      "b": 11,
      "countSmall": 16,
      "countLarge": 1963,
      "limitingDenominator": 40
    },
    {
      "a": 5,
      "b": 13,
      "countSmall": 13,
      "countLarge": 1648,
      "limitingDenominator": 48
    },
    {
      "a": 7,
      "b": 11,
      "countSmall": 13,
      "countLarge": 1294,
      "limitingDenominator": 60
    },
    {
      "a": 7,
      "b": 13,
      "countSmall": 9,
      "countLarge": 1078,
      "limitingDenominator": 72
    },
    {
      "a": 11,
      "b": 13,
      "countSmall": 8,
      "countLarge": 661,
      "limitingDenominator": 120
    }
  ],
  "certificate": {
    "coefficient": 49,
    "exponent": 594,
    "witness": 3,
    "digits": 181,
    "decimal": "3176972857424510233861062270638545256243904146560615751559175143044406058738007799587275709350126342501901506936777166717771287542112140470100888544868503447906217318229280729071617"
  }
} as const;
