import Hire.IdealNormLift15
import Mathlib.NumberTheory.NumberField.Cyclotomic.Three

namespace HireCharacterReadout

/-- The third cyclotomic field, Q(ζ₃). -/
abbrev DoorEisensteinField := CyclotomicField 3 ℚ

/-- Its ring of integers: the Eisenstein integers. -/
abbrev DoorEisensteinIntegers :=
  NumberField.RingOfIntegers DoorEisensteinField

/-- The door character lifted to ideals of the Eisenstein integers. -/
noncomputable def eisensteinIdealCharacter15 :
    Ideal DoorEisensteinIntegers →*₀ ℂ :=
  idealNormLift15

/-- The specialized character evaluates the table at the ideal norm. -/
theorem eisensteinIdealCharacter15_apply
    (I : Ideal DoorEisensteinIntegers) :
    eisensteinIdealCharacter15 I =
      complex15 (Ideal.absNorm I) := by
  exact idealNormLift15_apply I

/-- Multiplication of Eisenstein ideals multiplies their character values. -/
theorem eisensteinIdealCharacter15_mul
    (I J : Ideal DoorEisensteinIntegers) :
    eisensteinIdealCharacter15 (I * J) =
      eisensteinIdealCharacter15 I *
        eisensteinIdealCharacter15 J := by
  exact map_mul eisensteinIdealCharacter15 I J

/-- A unit generates the unit ideal, whose character value is 1. -/
theorem eisensteinIdealCharacter15_span_unit
    (u : DoorEisensteinIntegersˣ) :
    eisensteinIdealCharacter15
      (Ideal.span ({(u : DoorEisensteinIntegers)} :
        Set DoorEisensteinIntegers)) = 1 := by
  rw [Ideal.span_singleton_eq_top.mpr u.isUnit]
  rw [← Ideal.one_eq_top]
  exact map_one eisensteinIdealCharacter15

/--
An element congruent to 1 modulo 15 has algebraic norm
congruent to 1 modulo 15.
-/
theorem algebraicNorm_one_add_fifteen
    {S : Type*} [CommRing S] [Algebra ℤ S]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : @Module.Basis ι ℤ S _ _
      (Algebra.toModule : Module ℤ S))
    (x : S) :
    (Algebra.norm ℤ (1 + (15 : S) * x) : ZMod 15) = 1 := by
  let f : ℤ →+* ZMod 15 := Int.castRingHom (ZMod 15)
  change f (Algebra.norm ℤ (1 + (15 : S) * x)) = 1
  rw [Algebra.norm_eq_matrix_det b, RingHom.map_det]

  have h15 :
      f.mapMatrix (Algebra.leftMulMatrix b (15 : S)) = 0 := by
    simp only [map_ofNat]
    ext i j
    change (if i = j then (15 : ZMod 15) else 0) = 0
    have hzero : (15 : ZMod 15) = 0 := by
      exact_mod_cast (ZMod.natCast_self 15)
    simp only [hzero, ite_self]

  have hm :
      f.mapMatrix
        (Algebra.leftMulMatrix b (1 + (15 : S) * x)) = 1 := by
    rw [map_add, map_mul, map_one,
      map_add, map_mul, map_one, h15]
    simp

  rw [hm, Matrix.det_one]

theorem complexCharacter15_apply_neg_one :
    complexCharacter15 (-1 : ZMod 15) = 1 := by
  have h15 : (15 : ZMod 15) = 0 := by
    exact_mod_cast (ZMod.natCast_self 15)
  have h14 : ((14 : ℕ) : ZMod 15) = -1 := by
    norm_num only [Nat.cast_ofNat]
    linear_combination h15
  have h := complexCharacter15_apply_nat 14
  rw [h14] at h
  norm_num [complex15, quarticFive, Hire.chi3] at h
  exact h

/-- Taking absolute value preserves character value 1
when the signed integer is congruent to 1 modulo 15. -/
theorem complexCharacter15_natAbs_of_cast_eq_one
    (z : ℤ) (hz : (z : ZMod 15) = 1) :
    complexCharacter15 (z.natAbs : ZMod 15) = 1 := by
  cases z with
  | ofNat n =>
      have hn : (n : ZMod 15) = 1 := by
        simpa using hz
      simpa using congrArg complexCharacter15 hn
  | negSucc n =>
      have hn : -((n + 1 : ℕ) : ZMod 15) = 1 := by
        simpa using hz
      have hp : ((n + 1 : ℕ) : ZMod 15) = -1 := by
        linear_combination -hn
      simpa using
        (congrArg complexCharacter15 hp).trans
          complexCharacter15_apply_neg_one

/-- A principal ideal generated by 1 + 15x has character value 1. -/
theorem eisensteinIdealCharacter15_span_one_add_fifteen
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : @Module.Basis ι ℤ DoorEisensteinIntegers _ _
      (Algebra.toModule : Module ℤ DoorEisensteinIntegers))
    (x : DoorEisensteinIntegers) :
    eisensteinIdealCharacter15
      (Ideal.span
        ({1 + (15 : DoorEisensteinIntegers) * x} :
          Set DoorEisensteinIntegers)) = 1 := by
  change complexCharacter15
    (Ideal.absNorm
      (Ideal.span
        ({1 + (15 : DoorEisensteinIntegers) * x} :
          Set DoorEisensteinIntegers)) : ZMod 15) = 1
  rw [Ideal.absNorm_span_singleton]
  exact complexCharacter15_natAbs_of_cast_eq_one
    _ (algebraicNorm_one_add_fifteen b x)

/-- The principal-ideal congruence condition at modulus 15. -/
theorem eisensteinIdealCharacter15_span_of_congruent_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : @Module.Basis ι ℤ DoorEisensteinIntegers _ _
      (Algebra.toModule : Module ℤ DoorEisensteinIntegers))
    (a : DoorEisensteinIntegers)
    (ha : (15 : DoorEisensteinIntegers) ∣ a - 1) :
    eisensteinIdealCharacter15
      (Ideal.span ({a} : Set DoorEisensteinIntegers)) = 1 := by
  obtain ⟨x, hx⟩ := ha
  have he : a = 1 + (15 : DoorEisensteinIntegers) * x := by
    linear_combination hx
  rw [he]
  exact eisensteinIdealCharacter15_span_one_add_fifteen b x

end HireCharacterReadout
