import Hire.IdealNormLift15
import Mathlib.NumberTheory.NumberField.Cyclotomic.Three

namespace HireCharacterReadout

/-- The third cyclotomic field, Q(ζ₃). -/
abbrev DoorEisensteinField := CyclotomicField 3 ℚ

/-- Its ring of integers: the Eisenstein integers. -/
abbrev DoorEisensteinIntegers :=
  NumberField.RingOfIntegers DoorEisensteinField

/-- The door character lifted to ideals of the Eisenstein integers. -/
noncomputable def eisensteinIdealCharacter15 :
    Ideal DoorEisensteinIntegers →*₀ ℂ :=
  idealNormLift15

/-- The specialized character evaluates the table at the ideal norm. -/
theorem eisensteinIdealCharacter15_apply
    (I : Ideal DoorEisensteinIntegers) :
    eisensteinIdealCharacter15 I =
      complex15 (Ideal.absNorm I) := by
  exact idealNormLift15_apply I

/-- Multiplication of Eisenstein ideals multiplies their character values. -/
theorem eisensteinIdealCharacter15_mul
    (I J : Ideal DoorEisensteinIntegers) :
    eisensteinIdealCharacter15 (I * J) =
      eisensteinIdealCharacter15 I *
        eisensteinIdealCharacter15 J := by
  exact map_mul eisensteinIdealCharacter15 I J

/-- A unit generates the unit ideal, whose character value is 1. -/
theorem eisensteinIdealCharacter15_span_unit
    (u : DoorEisensteinIntegersˣ) :
    eisensteinIdealCharacter15
      (Ideal.span ({(u : DoorEisensteinIntegers)} :
        Set DoorEisensteinIntegers)) = 1 := by
  rw [Ideal.span_singleton_eq_top.mpr u.isUnit]
  rw [← Ideal.one_eq_top]
  exact map_one eisensteinIdealCharacter15

/--
An element congruent to 1 modulo 15 has algebraic norm
congruent to 1 modulo 15.
-/
theorem algebraicNorm_one_add_fifteen
    {S : Type*} [CommRing S] [Algebra ℤ S]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : @Module.Basis ι ℤ S _ _
      (Algebra.toModule : Module ℤ S))
    (x : S) :
    (Algebra.norm ℤ (1 + (15 : S) * x) : ZMod 15) = 1 := by
  let f : ℤ →+* ZMod 15 := Int.castRingHom (ZMod 15)
  change f (Algebra.norm ℤ (1 + (15 : S) * x)) = 1
  rw [Algebra.norm_eq_matrix_det b, RingHom.map_det]

  have h15 :
      f.mapMatrix (Algebra.leftMulMatrix b (15 : S)) = 0 := by
    simp only [map_ofNat]
    ext i j
    change (if i = j then (15 : ZMod 15) else 0) = 0
    have hzero : (15 : ZMod 15) = 0 := by
      exact_mod_cast (ZMod.natCast_self 15)
    simp only [hzero, ite_self]

  have hm :
      f.mapMatrix
        (Algebra.leftMulMatrix b (1 + (15 : S) * x)) = 1 := by
    rw [map_add, map_mul, map_one,
      map_add, map_mul, map_one, h15]
    simp

  rw [hm, Matrix.det_one]

theorem complexCharacter15_apply_neg_one :
    complexCharacter15 (-1 : ZMod 15) = 1 := by
  have h15 : (15 : ZMod 15) = 0 := by
    exact_mod_cast (ZMod.natCast_self 15)
  have h14 : ((14 : ℕ) : ZMod 15) = -1 := by
    norm_num only [Nat.cast_ofNat]
    linear_combination h15
  have h := complexCharacter15_apply_nat 14
  rw [h14] at h
  norm_num [complex15, quarticFive, Hire.chi3] at h
  exact h

/-- Taking absolute value preserves character value 1
when the signed integer is congruent to 1 modulo 15. -/
theorem complexCharacter15_natAbs_of_cast_eq_one
    (z : ℤ) (hz : (z : ZMod 15) = 1) :
    complexCharacter15 (z.natAbs : ZMod 15) = 1 := by
  cases z with
  | ofNat n =>
      have hn : (n : ZMod 15) = 1 := by
        simpa using hz
      simpa using congrArg complexCharacter15 hn
  | negSucc n =>
      have hn : -((n + 1 : ℕ) : ZMod 15) = 1 := by
        simpa using hz
      have hp : ((n + 1 : ℕ) : ZMod 15) = -1 := by
        linear_combination -hn
      simpa using
        (congrArg complexCharacter15 hp).trans
          complexCharacter15_apply_neg_one

/-- A principal ideal generated by 1 + 15x has character value 1. -/
theorem eisensteinIdealCharacter15_span_one_add_fifteen
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : @Module.Basis ι ℤ DoorEisensteinIntegers _ _
      (Algebra.toModule : Module ℤ DoorEisensteinIntegers))
    (x : DoorEisensteinIntegers) :
    eisensteinIdealCharacter15
      (Ideal.span
        ({1 + (15 : DoorEisensteinIntegers) * x} :
          Set DoorEisensteinIntegers)) = 1 := by
  change complexCharacter15
    (Ideal.absNorm
      (Ideal.span
        ({1 + (15 : DoorEisensteinIntegers) * x} :
          Set DoorEisensteinIntegers)) : ZMod 15) = 1
  rw [Ideal.absNorm_span_singleton]
  exact complexCharacter15_natAbs_of_cast_eq_one
    _ (algebraicNorm_one_add_fifteen b x)

/-- The principal-ideal congruence condition at modulus 15. -/
theorem eisensteinIdealCharacter15_span_of_congruent_one
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (b : @Module.Basis ι ℤ DoorEisensteinIntegers _ _
      (Algebra.toModule : Module ℤ DoorEisensteinIntegers))
    (a : DoorEisensteinIntegers)
    (ha : (15 : DoorEisensteinIntegers) ∣ a - 1) :
    eisensteinIdealCharacter15
      (Ideal.span ({a} : Set DoorEisensteinIntegers)) = 1 := by
  obtain ⟨x, hx⟩ := ha
  have he : a = 1 + (15 : DoorEisensteinIntegers) * x := by
    linear_combination hx
  rw [he]
  exact eisensteinIdealCharacter15_span_one_add_fifteen b x

/-- The principal congruence condition, with the basis chosen automatically. -/
theorem eisensteinIdealCharacter15_span_of_congruent_one_auto
    (a : DoorEisensteinIntegers)
    (ha : (15 : DoorEisensteinIntegers) ∣ a - 1) :
    eisensteinIdealCharacter15
      (Ideal.span ({a} : Set DoorEisensteinIntegers)) = 1 := by
  classical
  let : Module ℤ DoorEisensteinIntegers := Algebra.toModule
  let : Fintype
      (Module.Free.ChooseBasisIndex ℤ DoorEisensteinIntegers) :=
    Fintype.ofFinite _
  exact eisensteinIdealCharacter15_span_of_congruent_one
    (Module.Free.chooseBasis ℤ DoorEisensteinIntegers) a ha

/-- Algebraic norm congruence, with the basis chosen automatically. -/
theorem eisensteinNorm_one_add_fifteen
    (x : DoorEisensteinIntegers) :
    (Algebra.norm ℤ
      (1 + (15 : DoorEisensteinIntegers) * x) : ZMod 15) = 1 := by
  classical
  let : Module ℤ DoorEisensteinIntegers := Algebra.toModule
  let : Fintype
      (Module.Free.ChooseBasisIndex ℤ DoorEisensteinIntegers) :=
    Fintype.ofFinite _
  exact algebraicNorm_one_add_fifteen
    (Module.Free.chooseBasis ℤ DoorEisensteinIntegers) x

/-- An ideal coprime to 15 has norm coprime to 15. -/
theorem eisenstein_absNorm_coprime_fifteen
    (I : Ideal DoorEisensteinIntegers)
    (hI : IsCoprime I
      (Ideal.span ({(15 : DoorEisensteinIntegers)} :
        Set DoorEisensteinIntegers))) :
    Nat.Coprime (Ideal.absNorm I) 15 := by
  have htop :
      Ideal.span ({(15 : DoorEisensteinIntegers)} :
        Set DoorEisensteinIntegers) ⊔ I = ⊤ :=
    Ideal.isCoprime_iff_sup_eq.mp hI.symm
  have hmem :
      (1 : DoorEisensteinIntegers) ∈
        Ideal.span ({(15 : DoorEisensteinIntegers)} :
          Set DoorEisensteinIntegers) ⊔ I := by
    rw [htop]
    simp
  obtain ⟨x, y, hy, hxy⟩ :=
    Ideal.mem_span_singleton_sup.mp hmem
  have he :
      y = 1 + (15 : DoorEisensteinIntegers) * (-x) := by
    linear_combination hxy
  have hn :
      (Algebra.norm ℤ y : ZMod 15) = 1 := by
    rw [he]
    exact eisensteinNorm_one_add_fifteen (-x)
  obtain ⟨k, hk⟩ := Ideal.absNorm_dvd_norm_of_mem hy
  have hcast := congrArg (fun z : ℤ => (z : ZMod 15)) hk
  rw [hn] at hcast
  have hm :
      (Ideal.absNorm I : ZMod 15) * (k : ZMod 15) = 1 := by
    simpa only [Int.cast_mul, Int.cast_natCast] using hcast.symm
  have hu :
      IsUnit ((Ideal.absNorm I : ZMod 15) * (k : ZMod 15)) := by
    rw [hm]
    exact isUnit_one
  exact (ZMod.isUnit_iff_coprime (Ideal.absNorm I) 15).mp
    (isUnit_of_mul_isUnit_left hu)

/-- At inputs coprime to 15, the door character has fourth power 1. -/
theorem complexCharacter15_pow_four
    (n : ℕ) (hn : Nat.Coprime n 15) :
    complexCharacter15 (n : ZMod 15) ^ 4 = 1 := by
  have hg : Nat.gcd 15 (n % 15) = 1 := by
    calc
      Nat.gcd 15 (n % 15) =
          Nat.gcd (n % 15) 15 := Nat.gcd_comm _ _
      _ = Nat.gcd 15 n := (Nat.gcd_rec 15 n).symm
      _ = Nat.gcd n 15 := Nat.gcd_comm _ _
      _ = 1 := hn.gcd_eq_one
  have hlt : n % 15 < 15 := Nat.mod_lt n (by norm_num)
  rw [complexCharacter15_apply_nat, ← complex15_mod_fifteen]
  interval_cases h : n % 15 <;>
    norm_num [h, complex15, quarticFive,
      Hire.chi3, Complex.I_mul_I] at *

/-- On ideals coprime to the modulus, the lift has fourth power 1. -/
theorem eisensteinIdealCharacter15_pow_four
    (I : Ideal DoorEisensteinIntegers)
    (hI : IsCoprime I
      (Ideal.span ({(15 : DoorEisensteinIntegers)} :
        Set DoorEisensteinIntegers))) :
    eisensteinIdealCharacter15 I ^ 4 = 1 := by
  change complexCharacter15
    (Ideal.absNorm I : ZMod 15) ^ 4 = 1
  exact complexCharacter15_pow_four _
    (eisenstein_absNorm_coprime_fifteen I hI)

/-- Adding a multiple of 15 preserves the algebraic norm modulo 15. -/
theorem algebraicNorm_add_fifteen
    {S : Type*} [CommRing S] [Algebra ℤ S]
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (B : @Module.Basis ι ℤ S _ _
      (Algebra.toModule : Module ℤ S))
    (a x : S) :
    (Algebra.norm ℤ (a + (15 : S) * x) : ZMod 15) =
      (Algebra.norm ℤ a : ZMod 15) := by
  let f : ℤ →+* ZMod 15 := Int.castRingHom (ZMod 15)
  change f (Algebra.norm ℤ (a + (15 : S) * x)) =
    f (Algebra.norm ℤ a)
  rw [Algebra.norm_eq_matrix_det B,
    Algebra.norm_eq_matrix_det B,
    RingHom.map_det, RingHom.map_det]
  have h15 :
      f.mapMatrix (Algebra.leftMulMatrix B (15 : S)) = 0 := by
    simp only [map_ofNat]
    ext i j
    change (if i = j then (15 : ZMod 15) else 0) = 0
    have hzero : (15 : ZMod 15) = 0 := by
      exact_mod_cast (ZMod.natCast_self 15)
    simp only [hzero, ite_self]
  have hm :
      f.mapMatrix
        (Algebra.leftMulMatrix B (a + (15 : S) * x)) =
      f.mapMatrix (Algebra.leftMulMatrix B a) := by
    rw [map_add, map_mul, map_add, map_mul, h15]
    simp
  rw [hm]

/-- Absolute value does not change this even character's value. -/
theorem complexCharacter15_natAbs_eq (z : ℤ) :
    complexCharacter15 (z.natAbs : ZMod 15) =
      complexCharacter15 (z : ZMod 15) := by
  cases z with
  | ofNat n =>
      simp
  | negSucc n =>
      have he :
          (Int.negSucc n : ZMod 15) =
            (-1 : ZMod 15) * ((n + 1 : ℕ) : ZMod 15) := by
        simp
      have h := congrArg complexCharacter15 he
      rw [map_mul, complexCharacter15_apply_neg_one, one_mul] at h
      simpa using h.symm

/-- Congruent Eisenstein integers have congruent algebraic norms. -/
theorem eisensteinNorm_eq_of_congruent
    (a b : DoorEisensteinIntegers)
    (hab : (15 : DoorEisensteinIntegers) ∣ a - b) :
    (Algebra.norm ℤ a : ZMod 15) =
      (Algebra.norm ℤ b : ZMod 15) := by
  classical
  let : Module ℤ DoorEisensteinIntegers := Algebra.toModule
  let : Fintype
      (Module.Free.ChooseBasisIndex ℤ DoorEisensteinIntegers) :=
    Fintype.ofFinite _
  obtain ⟨x, hx⟩ := hab
  have he : a = b + (15 : DoorEisensteinIntegers) * x := by
    linear_combination hx
  rw [he]
  exact algebraicNorm_add_fifteen
    (Module.Free.chooseBasis ℤ DoorEisensteinIntegers) b x

/-- Congruent generators give equal principal-ideal character values. -/
theorem eisensteinIdealCharacter15_span_eq_of_congruent
    (a b : DoorEisensteinIntegers)
    (hab : (15 : DoorEisensteinIntegers) ∣ a - b) :
    eisensteinIdealCharacter15
        (Ideal.span ({a} : Set DoorEisensteinIntegers)) =
      eisensteinIdealCharacter15
        (Ideal.span ({b} : Set DoorEisensteinIntegers)) := by
  change
    complexCharacter15
        (Ideal.absNorm
          (Ideal.span ({a} : Set DoorEisensteinIntegers)) : ZMod 15) =
      complexCharacter15
        (Ideal.absNorm
          (Ideal.span ({b} : Set DoorEisensteinIntegers)) : ZMod 15)
  rw [Ideal.absNorm_span_singleton,
    Ideal.absNorm_span_singleton,
    complexCharacter15_natAbs_eq,
    complexCharacter15_natAbs_eq]
  exact congrArg complexCharacter15
    (eisensteinNorm_eq_of_congruent a b hab)

end HireCharacterReadout
